//peticiones usuarios
### Crear un nuevo usuario
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "userName": "tinitini",
    "password": "mamila",
    "email": "tinitini@gmail.com"
}

### Mostrar todos los usuarios
GET http://localhost:3000/api/users HTTP/1.1

### Mostrar un solo usuario
GET http://localhost:3000/api/users/8bb84e60-5369-416d-bc58-05ff7cc771af HTTP/1.1

### Actualizar un usuario
PUT http://localhost:3000/api/users/a564e4c3-cf68-4016-9d5e-c85977f746ce HTTP/1.1
Content-Type: application/json

{
    "userName": "fernandoquinteros",
    "password": "mamichula",
    "email": "fernandoquinteros@gmail.com"
}

### Eliminar un usuario
DELETE http://localhost:3000/api/users/752f9cce-69c4-4d6d-bd9d-e1f4c5bec571 HTTP/1.1

//peticiones habitaciones
### Crear una habitacion
POST http://localhost:3000/api/rooms HTTP/1.1
Content-Type: application/json

{
    "tipoHabitacion": "Duplex",
    "precio": 4000
}

### Mostrar todas las habitaciones
GET http://localhost:3000/api/rooms HTTP/1.1

### Mostrar una habitacion
GET http://localhost:3000/api/rooms/1 HTTP/1.1

### Actualizar el precio de una habitación
PATCH http://localhost:3000/api/rooms/1
Content-Type: application/json

{
    "precio": 3000
}

//Peticiones de las reservacion
###Crear una reservacion
POST http://localhost:3000/api/reservations HTTP/1.1
Content-Type: application/json

{
    "user": "8bb84e60-5369-416d-bc58-05ff7cc771af",
    "room": 1,
    "startDate": "2024-06-01",
    "endDate": "2024-08-10"
}

### Mostrar todas las reservaciones
GET http://localhost:3000/api/reservations HTTP/1.1

### Mostrar una reservacion
GET http://localhost:3000/api/reservations/3f021607-9135-406e-a776-bea11c5b0ceb HTTP/1.1

###Mostrar las reservaciones de un usuario
GET http://localhost:3000/api/users/731df729-4cb6-4857-9a58-ddcc6855ef97/reservations HTTP/1.1

### Actualizar una reservacion
PUT http://localhost:3000/api/reservations/3f021607-9135-406e-a776-bea11c5b0ceb HTTP/1.1
Content-Type: application/json

{
    "startDate": "2024-05-02",
    "endDate": "2024-05-10"
}

### Borrar una reservacion
DELETE http://localhost:3000/api/reservations/311070ca-f6a5-4a6e-b173-2831c5c015bf HTTP/1.1