//peticiones usuarios
### Crear un nuevo usuario
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "userName": "mariabecerra",
    "password": "mariabecerrax2000",
    "email": "mariabecerra@gmail.com"
}

### Mostrar todos los usuarios
GET http://localhost:3000/api/users HTTP/1.1

### Mostrar un solo usuario
GET http://localhost:3000/api/users/591854ec-7093-4a9f-96ae-122655c308e8 HTTP/1.1

### Actualizar un usuario
PUT http://localhost:3000/api/users/591854ec-7093-4a9f-96ae-122655c308e8 HTTP/1.1
Content-Type: application/json

{
    "userName": "mariabecerra",
    "password": "lamari2",
    "email": "mariabecerra@gmail.com"
}

### Eliminar un usuario
DELETE http://localhost:3000/api/users/591854ec-7093-4a9f-96ae-122655c308e8 HTTP/1.1





//peticiones habitaciones
### Crear una habitacion
POST http://localhost:3000/api/rooms HTTP/1.1
Content-Type: application/json

{
    "tipoHabitacion": "Duplex",
    "precio": 4000
}

### Mostrar todas las habitaciones
GET http://localhost:3000/api/rooms HTTP/1.1

### Mostrar una habitacion
GET http://localhost:3000/api/rooms/1 HTTP/1.1

### Actualizar el precio de una habitación
PATCH http://localhost:3000/api/rooms/1
Content-Type: application/json

{
    "precio": 3000
}





//Peticiones de las reservacion
###Crear una reservacion
POST http://localhost:3000/api/users/af34b560-6b49-442b-bc45-00dd499f0ca4/reservations HTTP/1.1
Content-Type: application/json

{
    "room": 2,
    "startDate": "2024-06-01",
    "endDate": "2024-08-10"
}

### Mostrar todas las reservaciones
GET http://localhost:3000/api/reservations HTTP/1.1

### Mostrar una reservación específica de un usuario
GET http://localhost:3000/api/users/abb4826e-c3b9-40e6-9f32-7993eda4a228/reservations/5fca9c3f-5af3-4098-90bc-e215153cf2ea HTTP/1.1

###Mostrar todas las reservaciones de un usuario
GET http://localhost:3000/api/users/abb4826e-c3b9-40e6-9f32-7993eda4a228/reservations HTTP/1.1

### Actualizar una reservacion
PUT http://localhost:3000/api/users/38b310ce-d001-46f1-972f-c6c8aab6e1ae/reservations/d31a9ac0-2595-4a78-87de-c5b093313e2d HTTP/1.1
Content-Type: application/json

{
    "room": 2,
    "startDate": "2024-05-02",
    "endDate": "2024-05-10"
}

### Borrar una reservacion
DELETE http://localhost:3000/api/users/38b310ce-d001-46f1-972f-c6c8aab6e1ae/reservations/d31a9ac0-2595-4a78-87de-c5b093313e2d HTTP/1.1